/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useMemo, useState } from 'react';
import { Check, ChevronLeft, ChevronRight, Minus, Plus, Send, MessageCircle } from 'lucide-react';
import ToyotaLayout from '@/components/ToyotaLayout';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { cn } from '@/lib/utils';
import { estimateBusinessCost, leaseIncludedItems } from '@/utils/businessMobility/costEstimator';
import { recommendVehicles } from '@/utils/businessMobility/vehicleRecommendations';
import { buildWhatsAppContinuationUrl } from '@/utils/businessMobility/whatsappContinuation';
import { mapToCrmPayload, submitBusinessMobilityLead } from '@/utils/businessMobility/crmPayloadMapper';
import { trackBusinessBuilderEvent } from '@/utils/businessMobility/analytics';
import { BusinessBuilderState, LeadFormData, RecommendedVehicle } from '@/utils/businessMobility/types';

const steps = ['Intro','Business','Usage','Vehicles','Ownership','Add-ons','Estimate','Proposal','Lead','Done'];
const businessTypes = ['SME','Corporate fleet','Delivery / logistics','Construction','Real estate','Rental company','Government','School / transport','Hospitality','Field service','Personal business owner'];
const companySizes = ['1–10 employees','11–50 employees','51–200 employees','200+ employees'];
const emirates = ['Dubai','Abu Dhabi','Sharjah','Ajman','Ras Al Khaimah','Fujairah','Umm Al Quwain'];
const timelines = ['Immediately','Within 30 days','1–3 months','3+ months','Researching only'];
const useCases = ['Sales team','Delivery / light cargo','Construction / site operations','Staff transport','Executive mobility','Rental fleet','Field service','Mixed fleet'];
const allAddOns = ['Service maintenance contract','Extended warranty','Insurance','Registration support','Rustproofing','Paint protection film','Ceramic coating','Window tinting','Branding / wrapping','Replacement vehicle','Roadside recovery','Driver safety kit','Telematics / tracking'];
const defaultState: BusinessBuilderState = { businessType:'', companySize:'', vehicleCount:1, emirate:'', industry:'', purchaseTimeline:'', existingFleet:'', useCase:'', dailyMileage:'', passengerRequirement:'', cargoRequirement:'', offRoadRequirement:'', fuelEfficiencyPriority:'', needHybrid:'', needCommercialRegistration:'', vehicles:[], ownership:'Not sure', leaseDuration:'36 months', annualMileage:'60,000 km', selectedAddOns:['Service maintenance contract','Insurance','Registration support','Roadside recovery']};
const emptyLead: LeadFormData = { firstName:'', lastName:'', mobile:'', email:'', companyName:'', industry:'', preferredContactMethod:'WhatsApp', comments:'', tradeLicense:'', existingFleetSize:'', currentBrand:'', needTradeIn:'', website:'', trn:'' };
const money = (v:number)=>`AED ${Math.round(v).toLocaleString()}`;
const isUaeMobile = (v:string)=>/^(\+971|00971|971|0)?5[0-9]{8}$/.test(v.replace(/[\s-]/g,''));
function SelectField({label,value,onChange,options,error}:{label:string;value:string;onChange:(v:string)=>void;options:string[];error?:string}){return <div><Label>{label}</Label><select className="mt-2 w-full rounded-md border border-input bg-white px-3 py-2 text-sm" value={value} onChange={e=>onChange(e.target.value)}><option value="">Select</option>{options.map(o=><option key={o}>{o}</option>)}</select>{error&&<p className="mt-1 text-sm text-red-600">{error}</p>}</div>}
function Field({label,value,onChange,type='text',error}:{label:string;value:string|number;onChange:(v:string)=>void;type?:string;error?:string}){return <div><Label>{label}</Label><Input className="mt-2" type={type} value={value} onChange={e=>onChange(e.target.value)} />{error&&<p className="mt-1 text-sm text-red-600">{error}</p>}</div>}
export function Stepper({step}:{step:number}){return <div className="mb-8"><div className="flex items-center gap-2 overflow-x-auto pb-2">{steps.slice(0,9).map((s,i)=><div key={s} className="flex min-w-fit items-center gap-2"><span className={cn('grid h-8 w-8 place-items-center rounded-full text-xs font-bold',i<=step?'bg-[hsl(var(--toyota-red))] text-white':'bg-gray-200 text-gray-600')}>{i<step?<Check size={14}/>:i+1}</span><span className="hidden text-xs font-medium text-gray-600 sm:inline">{s}</span></div>)}</div><div className="mt-3 h-1 rounded-full bg-gray-200"><div className="h-1 rounded-full bg-[hsl(var(--toyota-red))] transition-all" style={{width:`${Math.min(100,(step/8)*100)}%`}} /></div></div>}
function Chip({active,children,onClick}:{active?:boolean;children:React.ReactNode;onClick:()=>void}){return <button type="button" onClick={onClick} className={cn('rounded-xl border p-4 text-left font-medium transition hover:border-red-400',active?'border-[hsl(var(--toyota-red))] bg-red-50 text-red-700':'border-gray-200 bg-white')}>{children}</button>}
export function VehicleCard({vehicle,onQty}:{vehicle:RecommendedVehicle;onQty:(q:number)=>void}){return <Card className="overflow-hidden"><CardContent className="p-5"><div className="mb-4 h-28 rounded-xl bg-gradient-to-br from-gray-100 to-gray-200 grid place-items-center text-2xl font-bold text-gray-400">{vehicle.model}</div><div className="flex justify-between gap-4"><div><h3 className="text-xl font-bold">{vehicle.model}</h3><p className="text-sm text-gray-500">{vehicle.category}</p></div><span className="text-sm font-semibold">From {money(vehicle.startingPrice)}</span></div><p className="mt-3 text-sm text-gray-600">{vehicle.reason}</p><p className="mt-2 text-sm font-semibold">Estimated monthly placeholder: {money(vehicle.startingPrice/60)}</p><div className="mt-4 flex items-center justify-between"><div className="flex items-center gap-2"><Button size="icon" variant="outline" onClick={()=>onQty(Math.max(0,vehicle.quantity-1))}><Minus/></Button><span className="w-8 text-center font-bold">{vehicle.quantity}</span><Button size="icon" onClick={()=>onQty(vehicle.quantity+1)}><Plus/></Button></div><div className="flex gap-2"><Button variant="ghost" size="sm">Replace model</Button><Button variant="outline" size="sm">View details</Button></div></div></CardContent></Card>}
export function AddOnCard({name,selected,included,onClick}:{name:string;selected:boolean;included:boolean;onClick:()=>void}){return <button type="button" disabled={included} onClick={onClick} className={cn('rounded-xl border p-4 text-left transition',included?'border-green-300 bg-green-50':selected?'border-red-500 bg-red-50':'border-gray-200 bg-white hover:border-red-300')}><div className="font-semibold">{name}</div><div className="text-sm text-gray-500">{included?'Included with Drive-on-Lease':selected?'Selected':'Optional business support'}</div></button>}
export function CostBreakdown({estimate}:{estimate:ReturnType<typeof estimateBusinessCost>}){return <Card><CardContent className="space-y-4 p-6"><div className="flex justify-between"><span>Vehicle cost</span><b>{money(estimate.vehicleMonthlyCost)}/mo</b></div><div className="flex justify-between"><span>Optional add-ons</span><b>{money(estimate.addOnsMonthlyCost)}/mo</b></div><div className="border-t pt-4 flex justify-between text-xl"><span>Estimated total monthly cost</span><b className="text-red-600">{money(estimate.totalMonthlyCost)}</b></div><div className="flex justify-between"><span>One-time estimated vehicle value</span><b>{money(estimate.totalVehicleValue)}</b></div><p className="text-sm text-gray-500">Final pricing, availability, approvals, lease terms, and fleet discounts will be confirmed by a Toyota business advisor.</p></CardContent></Card>}
export function StickyJourneyCTA({step,onBack,onNext,nextLabel='Next'}:{step:number;onBack:()=>void;onNext:()=>void;nextLabel?:string}){return <div className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 p-3 backdrop-blur md:hidden"><div className="flex gap-3"><Button variant="outline" className="flex-1" onClick={onBack} disabled={step===0}><ChevronLeft/>Back</Button><Button className="flex-1" onClick={onNext}>{nextLabel}<ChevronRight/></Button></div></div>}
export const BusinessProfileStep=({state,setState,errors}:any)=><section><h2 className="text-3xl font-bold">Tell us about your business</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><SelectField label="Business type" value={state.businessType} onChange={v=>setState({businessType:v})} options={businessTypes} error={errors.businessType}/><SelectField label="Company size" value={state.companySize} onChange={v=>setState({companySize:v})} options={companySizes} error={errors.companySize}/><Field label="Number of vehicles needed" type="number" value={state.vehicleCount} onChange={v=>setState({vehicleCount:Number(v)})} error={errors.vehicleCount}/><SelectField label="Main emirate" value={state.emirate} onChange={v=>setState({emirate:v})} options={emirates} error={errors.emirate}/><Field label="Industry" value={state.industry} onChange={v=>setState({industry:v})} error={errors.industry}/><SelectField label="Purchase timeline" value={state.purchaseTimeline} onChange={v=>setState({purchaseTimeline:v})} options={timelines} error={errors.purchaseTimeline}/><SelectField label="Existing fleet" value={state.existingFleet} onChange={v=>setState({existingFleet:v})} options={['Yes','No']}/></div></section>;
export const UsageNeedStep=({state,setState,errors}:any)=><section><h2 className="text-3xl font-bold">What will the vehicles be used for?</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{useCases.map(u=><Chip key={u} active={state.useCase===u} onClick={()=>setState({useCase:u})}>{u}</Chip>)}</div>{errors.useCase&&<p className="mt-2 text-sm text-red-600">{errors.useCase}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2"><SelectField label="Daily mileage band" value={state.dailyMileage} onChange={v=>setState({dailyMileage:v})} options={['Less than 50 km/day','50–100 km/day','100–200 km/day','200+ km/day']} error={errors.dailyMileage}/><SelectField label="Passenger requirement" value={state.passengerRequirement} onChange={v=>setState({passengerRequirement:v})} options={['1–2 passengers','3–5 passengers','6–10 passengers','10+ passengers']} error={errors.passengerRequirement}/><SelectField label="Cargo requirement" value={state.cargoRequirement} onChange={v=>setState({cargoRequirement:v})} options={['None','Light cargo','Medium cargo','Heavy cargo']} error={errors.cargoRequirement}/><SelectField label="Off-road requirement" value={state.offRoadRequirement} onChange={v=>setState({offRoadRequirement:v})} options={['No','Sometimes','Frequent']} error={errors.offRoadRequirement}/><SelectField label="Fuel efficiency priority" value={state.fuelEfficiencyPriority} onChange={v=>setState({fuelEfficiencyPriority:v})} options={['Low','Medium','High']} error={errors.fuelEfficiencyPriority}/><SelectField label="Need hybrid?" value={state.needHybrid} onChange={v=>setState({needHybrid:v})} options={['Yes','No','Not sure']} error={errors.needHybrid}/><SelectField label="Need commercial registration?" value={state.needCommercialRegistration} onChange={v=>setState({needCommercialRegistration:v})} options={['Yes','No','Not sure']} error={errors.needCommercialRegistration}/></div></section>;
export const VehicleRecommendationStep=({state,setState}:any)=><section><h2 className="text-3xl font-bold">Recommended Toyota business package</h2><p className="mt-2 text-gray-600">Rule-based MVP recommendation for {state.useCase}.</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{state.vehicles.map((v:RecommendedVehicle)=><VehicleCard key={v.model} vehicle={v} onQty={q=>{setState({vehicles:state.vehicles.map((x:RecommendedVehicle)=>x.model===v.model?{...x,quantity:q}:x), vehicleCount: state.vehicles.map((x:RecommendedVehicle)=>x.model===v.model?{...x,quantity:q}:x).reduce((s:number,x:RecommendedVehicle)=>s+x.quantity,0)}); trackBusinessBuilderEvent('model_quantity_updated',state,undefined,{model:v.model,quantity:q});}} />)}</div></section>;
export const OwnershipOptionStep=({state,setState}:any)=><section><h2 className="text-3xl font-bold">Choose how your business wants to operate</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{[['Buy','Best for businesses that want ownership and long-term asset value.'],['Finance','Best for businesses that want ownership with monthly payments.'],['Drive-on-Lease','Best for businesses that want predictable monthly cost with service, insurance, registration, and support included.']].map(([o,d])=><Chip key={o} active={state.ownership===o} onClick={()=>{setState({ownership:o}); trackBusinessBuilderEvent('ownership_option_selected',{...state,ownership:o} as any)}}><h3 className="text-xl font-bold">{o}</h3><p className="mt-2 text-sm text-gray-600">{d}</p></Chip>)}</div>{state.ownership==='Drive-on-Lease'&&<div className="mt-6 grid gap-4 md:grid-cols-2"><SelectField label="Lease duration" value={state.leaseDuration} onChange={v=>setState({leaseDuration:v})} options={['24 months','36 months']}/><SelectField label="Annual mileage" value={state.annualMileage} onChange={v=>setState({annualMileage:v})} options={['40,000 km','60,000 km','80,000 km','100,000 km','120,000 km']}/><div className="md:col-span-2 rounded-xl bg-gray-50 p-4 text-sm">Service and maintenance, insurance, registration management, breakdown and recovery, and fine/toll administration included.</div></div>}</section>;
export const AddOnsStep=({state,setState}:any)=><section><h2 className="text-3xl font-bold">Add business support options</h2><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{allAddOns.map(a=>{const included=state.ownership==='Drive-on-Lease'&&leaseIncludedItems.includes(a); const selected=state.selectedAddOns.includes(a)||included; return <AddOnCard key={a} name={a} selected={selected} included={included} onClick={()=>{const next=selected?state.selectedAddOns.filter((x:string)=>x!==a):[...state.selectedAddOns,a]; setState({selectedAddOns:next}); trackBusinessBuilderEvent('business_addon_selected',state,undefined,{add_on:a,selected:!selected});}}/>})}</div></section>;
export const CostEstimateStep=({estimate}:{estimate:ReturnType<typeof estimateBusinessCost>})=><section><h2 className="text-3xl font-bold">Estimated Business Mobility Cost</h2><div className="mt-6"><CostBreakdown estimate={estimate}/></div></section>;
export const ProposalSummaryStep=({state,estimate,onWhatsapp}:any)=><section><h2 className="text-3xl font-bold">Your Toyota Business Mobility Proposal</h2><div className="mt-6 grid gap-5 lg:grid-cols-2"><Card><CardContent className="space-y-3 p-6">{[['Business type',state.businessType],['Industry',state.industry],['Emirate',state.emirate],['Number of vehicles',state.vehicleCount],['Use case',state.useCase],['Ownership preference',state.ownership],['Lease duration',state.ownership==='Drive-on-Lease'?`${state.leaseDuration} / ${state.annualMileage}`:'N/A'],['Purchase timeline',state.purchaseTimeline]].map(([k,v])=><div className="flex justify-between gap-4" key={k}><span className="text-gray-500">{k}</span><b>{v}</b></div>)}</CardContent></Card><CostBreakdown estimate={estimate}/></div><div className="mt-6 flex flex-wrap gap-3"><Button onClick={()=>null}>Submit to Toyota Business Team</Button><Button variant="outline">Edit package</Button><Button variant="outline" onClick={onWhatsapp}><MessageCircle/>Continue on WhatsApp</Button><Button variant="ghost">Download summary placeholder</Button><Button variant="ghost">Email summary placeholder</Button></div></section>;
export function LeadCaptureStep({lead,setLead,errors,onSubmit,submitting}:any){return <section><h2 className="text-3xl font-bold">Submit your business request</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="First name" value={lead.firstName} onChange={v=>setLead({firstName:v})} error={errors.firstName}/><Field label="Last name" value={lead.lastName} onChange={v=>setLead({lastName:v})} error={errors.lastName}/><Field label="Mobile number" value={lead.mobile} onChange={v=>setLead({mobile:v})} error={errors.mobile}/><Field label="Email" value={lead.email} onChange={v=>setLead({email:v})} error={errors.email}/><Field label="Company name" value={lead.companyName} onChange={v=>setLead({companyName:v})} error={errors.companyName}/><Field label="Industry" value={lead.industry} onChange={v=>setLead({industry:v})} error={errors.industry}/><SelectField label="Preferred contact method" value={lead.preferredContactMethod} onChange={v=>setLead({preferredContactMethod:v})} options={['WhatsApp','Call','Email']} error={errors.preferredContactMethod}/><Field label="Trade license upload placeholder" value={lead.tradeLicense} onChange={v=>setLead({tradeLicense:v})}/><Field label="Existing fleet size" value={lead.existingFleetSize} onChange={v=>setLead({existingFleetSize:v})}/><Field label="Current brand used" value={lead.currentBrand} onChange={v=>setLead({currentBrand:v})}/><SelectField label="Need trade-in?" value={lead.needTradeIn} onChange={v=>setLead({needTradeIn:v})} options={['Yes','No','Not sure']}/><Field label="Company website" value={lead.website} onChange={v=>setLead({website:v})}/><Field label="VAT/TRN number" value={lead.trn} onChange={v=>setLead({trn:v})}/><div className="md:col-span-2"><Label>Comments optional</Label><Textarea className="mt-2" value={lead.comments} onChange={e=>setLead({comments:e.target.value})}/></div></div><Button className="mt-6" disabled={submitting} onClick={onSubmit}><Send/>Submit your business request</Button></section>}
export function ConfirmationStep({payload,estimate,whatsappUrl}:any){return <section><h2 className="text-3xl font-bold">Your request has been submitted</h2><p className="mt-3 text-gray-600">Thank you. Your Toyota Business Mobility request has been received. A Toyota business advisor will contact you with a tailored proposal.</p><div className="mt-6 grid gap-5 lg:grid-cols-2"><Card><CardContent className="space-y-3 p-6"><div className="flex justify-between"><span>Lead score</span><b>{payload?.leadScore}</b></div><div className="flex justify-between"><span>Assigned team</span><b>{payload?.routingTeam}</b></div><div className="flex justify-between"><span>Reference</span><b>{payload?.leadReferenceId || 'Generated'}</b></div></CardContent></Card><CostBreakdown estimate={estimate}/></div><Button className="mt-6" asChild><a href={whatsappUrl} target="_blank" rel="noreferrer"><MessageCircle/>Continue on WhatsApp</a></Button></section>}
export default function BusinessBuilderPage(){const [step,setStep]=useState(0); const [state,setWholeState]=useState(defaultState); const [lead,setWholeLead]=useState(emptyLead); const [errors,setErrors]=useState<Record<string,string>>({}); const [submitting,setSubmitting]=useState(false); const [payload,setPayload]=useState<any>(null); const estimate=useMemo(()=>estimateBusinessCost(state),[state]); const setState=(patch:Partial<BusinessBuilderState>)=>setWholeState(s=>({...s,...patch})); const setLead=(patch:Partial<LeadFormData>)=>setWholeLead(l=>({...l,...patch})); const whatsappUrl=buildWhatsAppContinuationUrl(state,lead,estimate);
function validateStep(){const e:Record<string,string>={}; if(step===1){['businessType','companySize','emirate','industry','purchaseTimeline'].forEach(k=>{if(!(state as any)[k])e[k]='Required'}); if(!state.vehicleCount || state.vehicleCount<1)e.vehicleCount='Vehicle count must be greater than zero';} if(step===2){['useCase','dailyMileage','passengerRequirement','cargoRequirement','offRoadRequirement','fuelEfficiencyPriority','needHybrid','needCommercialRegistration'].forEach(k=>{if(!(state as any)[k])e[k]='Required'});} if(step===8){['firstName','lastName','mobile','email','companyName','industry','preferredContactMethod'].forEach(k=>{if(!(lead as any)[k])e[k]='Required'}); if(lead.email && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(lead.email)) e.email='Enter a valid email'; if(lead.mobile && !isUaeMobile(lead.mobile)) e.mobile='Enter a valid UAE mobile number'; if(state.vehicleCount<1)e.vehicleCount='Vehicle count must be greater than zero';} setErrors(e); return Object.keys(e).length===0;}
function next(){ if(!validateStep()) return; if(step===0) trackBusinessBuilderEvent('business_builder_start',state); if(step===1) trackBusinessBuilderEvent('business_profile_completed',state); if(step===2){const vehicles=recommendVehicles(state.useCase,state.vehicleCount); setState({vehicles}); trackBusinessBuilderEvent('business_use_case_selected',{...state,vehicles});} if(step===3) trackBusinessBuilderEvent('recommended_models_viewed',state); if(step===6) trackBusinessBuilderEvent('cost_summary_viewed',state,estimate); if(step===7) trackBusinessBuilderEvent('proposal_summary_viewed',state,estimate); setStep(s=>Math.min(8,s+1)); window.scrollTo({top:0,behavior:'smooth'});}
async function submit(){ if(!validateStep()) return; setSubmitting(true); try{const crm=mapToCrmPayload(state,lead,estimate); const result=await submitBusinessMobilityLead(crm); const finalPayload={...crm,...result}; setPayload(finalPayload); trackBusinessBuilderEvent('business_lead_submitted',state,estimate,{lead_score:crm.leadScore,routing_team:crm.routingTeam}); setStep(9);}catch(err){trackBusinessBuilderEvent('business_lead_submit_failed',state,estimate,{error:String(err)}); setErrors({submit:'Submission failed. Please try again.'});} finally{setSubmitting(false);}}
function whatsapp(){trackBusinessBuilderEvent('whatsapp_continue_clicked',state,estimate); window.open(whatsappUrl,'_blank','noopener,noreferrer');}
return <ToyotaLayout activeNavItem="business"><div className="bg-gradient-to-b from-gray-50 to-white pb-28 md:pb-12"><section className="mx-auto max-w-7xl px-4 py-8 md:py-12"><Stepper step={Math.min(step,8)}/>{step===0&&<section className="grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><div><p className="font-semibold text-red-600">Build My Business Fleet</p><h1 className="mt-3 text-4xl font-black tracking-tight md:text-6xl">Toyota Business Mobility Builder</h1><p className="mt-5 max-w-3xl text-lg text-gray-600">Build a complete Toyota mobility package for your business — from vehicle selection to lease, finance, service, insurance, registration, and support.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" onClick={next}>Start Building</Button><Button size="lg" variant="outline" onClick={whatsapp}><MessageCircle/>Continue on WhatsApp</Button></div></div><div className="grid gap-3">{['Built for SMEs, fleets, and business owners','Buy, finance, or lease','Commercial and passenger Toyota vehicles','Service, insurance, registration, and warranty support','Proposal-ready summary','Continue on WhatsApp'].map(c=><Card key={c}><CardContent className="flex items-center gap-3 p-4"><Check className="text-red-600"/>{c}</CardContent></Card>)}</div></section>}{step===1&&<BusinessProfileStep state={state} setState={setState} errors={errors}/>} {step===2&&<UsageNeedStep state={state} setState={setState} errors={errors}/>} {step===3&&<VehicleRecommendationStep state={state} setState={setState}/>} {step===4&&<OwnershipOptionStep state={state} setState={setState}/>} {step===5&&<AddOnsStep state={state} setState={setState}/>} {step===6&&<CostEstimateStep estimate={estimate}/>} {step===7&&<ProposalSummaryStep state={state} estimate={estimate} onWhatsapp={whatsapp}/>} {step===8&&<LeadCaptureStep lead={lead} setLead={setLead} errors={errors} onSubmit={submit} submitting={submitting}/>} {step===9&&<ConfirmationStep payload={payload} estimate={estimate} whatsappUrl={whatsappUrl}/>} {errors.submit&&<p className="mt-4 text-red-600">{errors.submit}</p>} {step>0&&step<9&&<div className="mt-8 hidden justify-between md:flex"><Button variant="outline" onClick={()=>setStep(s=>Math.max(0,s-1))}><ChevronLeft/>Back</Button><Button onClick={step===8?submit:next}>{step===8?'Submit':'Next'}<ChevronRight/></Button></div>}<aside className="mt-10 rounded-2xl border bg-white p-5 shadow-sm lg:fixed lg:right-6 lg:top-32 lg:w-72"><h3 className="font-bold">Package snapshot</h3><p className="mt-2 text-sm text-gray-600">{state.vehicleCount} vehicles • {state.ownership}</p><p className="mt-1 text-sm text-gray-600">{state.vehicles.map(v=>`${v.model} x${v.quantity}`).join(', ') || 'Recommendations pending'}</p><p className="mt-3 font-bold text-red-600">{money(estimate.totalMonthlyCost)}/mo</p></aside></section>{step>0&&step<9&&<StickyJourneyCTA step={step} onBack={()=>setStep(s=>Math.max(0,s-1))} onNext={step===8?submit:next} nextLabel={step===8?'Submit':'Next'}/>}</div></ToyotaLayout>}
